name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, windows-2022]

    steps:
      - uses: actions/checkout@v6
    
      - name: Fail the job
        run: exit 1

      - name: Debug failed job
        if: ${{ failure() }}
        uses: ./
        with:
          ports: "22,3389,5900"
          new-password: ${{ secrets.DEBUG_PASSWORD }}
